
Exercise 1 Simulated Annealing for TSP



In the TSP, the goal is to find the shortest possible route that visits each city exactly once and returns to the starting city



Imports

In [29]:
import os

#import matplotlib.pyplot as plt

import numpy as np
import matplotlib as plt

1. Implement compute_total_cost in hw2.py which takes a solution x and a distance
matrix and computes the total cost of the route corresponding to x. (1 point)


In [35]:

def compute_total_cost(solution, distances):
    """Compute the total cost of a given solution

    Examples
    --------
    >>> solution = np.array([0, 1, 2, 3, 4, 5])
    >>> distances = np.array([
    ...    [0, 5, 3, 4, 2, 3],
    ...    [5, 0, 2, 8, 3, 9],
    ...    [3, 2, 0, 2, 5, 8],
    ...    [4, 8, 2, 0, 6, 9],
    ...    [2, 3, 5, 6, 0, 1],
    ...    [3, 9, 8, 9, 1, 0],
    ... ], dtype=float)
    >>> compute_total_cost(solution, distances)
    19.0

    Parameters
    ----------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the solution whose length is to be computed.
    distances : ndarray
        2D array of shape (n_cities, n_cities) with `float` dtype
        representing the distance matrix.

    Returns
    -------
    length : float
    """
    # Question 1
    # Initialise the total cost to zero.
    total_cost = 0.0

    # Compute the total cost of the solution by summing the distances between consecutive cities in the solution.
    for i in range(len(solution)):
        total_cost += distances[solution[i], solution[(i+1)%len(solution)]]

    return total_cost

"""

    # Question 1
    n_cities = solution.shape[0]
    cost = 0.0
    for i in range(n_cities):
        j = (i + 1) % n_cities
        cost += distances[solution[i], solution[j]]
    return cost
"""

'\n\n    # Question 1\n    n_cities = solution.shape[0]\n    cost = 0.0\n    for i in range(n_cities):\n        j = (i + 1) % n_cities\n        cost += distances[solution[i], solution[j]]\n    return cost\n'

In [36]:
#test
solution = np.array([0, 1, 2, 3, 4, 5])
distances = np.array([[0, 5, 3, 4, 2, 3],
                      [5, 0, 2, 8, 3, 9],
                      [3, 2, 0, 2, 5, 8],
                      [4, 8, 2, 0, 6, 9],
                      [2, 3, 5, 6, 0, 1],
                      [3, 9, 8, 9, 1, 0],
                      ], dtype=float)
compute_total_cost(solution, distances)

19.0


2. Implement run_greedy_heuristic in hw2.py which takes a distance matrix and runs
Algorithm 1.

- First, the n variable is set to the number of cities in the problem, which is determined by the size of the distances matrix.

- Next, the c variable is set to 0, which is the starting city for the TSP. The S variable is set to a set containing all cities except the starting city. The x variable is set to an array containing only the starting city.

- A for loop is used to iterate through each remaining city in the TSP.

- Within the for loop, the closest_city variable is set to the city in S that is closest to the current city c. This is accomplished using the argmin function from NumPy to find the index of the smallest value in the row of distances corresponding to the current city, and then using this index to look up the corresponding city in S.

- The closest_city is then removed from S, and added to the end of the x array using the append method.

- Finally, the closest_city becomes the new c, and the for loop continues to the next city.

- Once all cities have been visited, the x array containing the tour is returned as the solution.

In [7]:

def run_greedy_heuristic(distances):
    """Run a greedy heuristic for TSP

    This runs a greedy heuristic for TSP and return a feasible solution.
    This starts at city 0 and creates a soltuion by finding the shortest
    cities greedily.

    Examples
    --------
    >>> distances = np.array([
    ...    [0, 5, 3, 4, 2, 3],
    ...    [5, 0, 2, 8, 3, 9],
    ...    [3, 2, 0, 2, 5, 8],
    ...    [4, 8, 2, 0, 6, 9],
    ...    [2, 3, 5, 6, 0, 1],
    ...    [3, 9, 8, 9, 1, 0],
    ... ], dtype=float)
    >>> run_greedy_heuristic(distances)
    array([0, 4, 5, 2, 1, 3])
    >>> compute_total_cost(run_greedy_heuristic(distances), distances)
    25.0

    Parameters
    ----------
    distances : ndarray
        2D array of shape (n_cities, n_cities) with `float` dtype
        representing the distance matrix.

    Returns
    -------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the solution obtained by the greedy heuristic.
    """



#    c = 0
#    x = c.sort()

    n = distances.shape[0]

    # Start at city 0
    c = 0
    S = set(range(1, n))
    x = np.array([c], dtype=int)

    # Find the closest city to c and add it to the solution
    for i in range(n-1):
        closest_city = min(S, key=lambda j: distances[c][j])
        S.remove(closest_city)
        x = np.append(x, closest_city)
        c = closest_city

    return x

In [123]:
    
distances = np.array([
    [0, 5, 3, 4, 2, 3],
    [5, 0, 2, 8, 3, 9],
    [3, 2, 0, 2, 5, 8],
    [4, 8, 2, 0, 6, 9],
    [2, 3, 5, 6, 0, 1],
    [3, 9, 8, 9, 1, 0],], dtype=float)



run_greedy_heuristic(distances)


array([0, 4, 5, 2, 1, 3])

array([0, 2, 1, 3])

In [124]:
compute_total_cost(run_greedy_heuristic(distances), distances)

25.0

In [13]:


'''
    run_greedy_heuristic(distances)
    array([0, 4, 5, 2, 1, 3])
    compute_total_cost(run_greedy_heuristic(distances), distances)
    #25.0

'''

'\n    run_greedy_heuristic(distances)\n    array([0, 4, 5, 2, 1, 3])\n    compute_total_cost(run_greedy_heuristic(distances), distances)\n    #25.0\n\n'

3. Implement sample_two_opt in hw2.py which takes a solution x and samples a solution
uniformly from N (x), where N (x) is the set of neighbouring solutions obtained
by applying two-opt to x (see Algorithm 2).1 (1 point)

In [106]:
def sample_two_opt(solution):
    """Return a neighbour of a given solution based on two-opt

    This returns a neighbouring solution.

    Examples
    --------
    >>> solution = np.array([0, 1, 2, 3])
    >>> sample_two_opt(solution)  
    array([0, 2, 1, 3])

    Parameters
    ----------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the current solution.

    Returns
    -------
    new_solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the sampled solution.
    """

    """
    n_cities = len(solution)
    i, j = np.random.choice(n_cities, size=2, replace=False)
    i, j = min(i, j), max(i, j)
    new_solution = np.concatenate((solution[:i], solution[i:j+1][::-1], solution[j+1:]))
    return new_solution
    """

    n_cities = len(solution)
    i, j = np.random.choice(n_cities, size=2, replace=False)
    i, j = min(i, j), max(i, j)
    new_solution = np.concatenate((solution[:i], solution[i:j+1][::-1], solution[j+1:]))
    return new_solution


In [113]:
solution = np.array([0, 1, 2, 3])
sample_two_opt(solution) 

array([0, 3, 2, 1])

4. Implement run_simulated_annealing in hw2.py and run simulated annealing for 20
times using the distance matrix provided in distances.npy. Plot the objective values
of the iterates (see Figure 1 for the format of the plot). Make sure the plot is readable
(e.g. put axis labels). (3 points)

In [125]:
import matplotlib.pyplot as plt

def run_simulated_annealing(
    initial_solution,
    objective,
    sample,
    n_epochs,
    temperature,
):
    """Run simulated annealing

    Parameters
    ----------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the initial solution.
    objective : callable
        Objective function of the following signature:
        (solution: ndarray of shape (n_cities,)) -> float.
    sample : callable
        A function to sample a neighbouring solution.
        This should have the following signature:
        (solution: ndarray of shape (n_cities,))
        -> ndarray of shape (n_cities,).
    n_epochs : int
        Number of epochs
    temperature : callable
        A function to compute the temperature.
        This should have the following signature:
        (epoch: int) -> float.

    Returns
    -------
    objective : float
        The objective value of the best solution found.
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the best solution found.
    objective_list : list of float
        The objective values of the iterates
    """
    current_solution = initial_solution.copy()
    current_best_objective = objective(current_solution)
    best_solution = current_solution.copy()
    best_objective = current_best_objective
    objective_list = [current_best_objective]

    for epoch in range(n_epochs):
        neighbour_solution = sample(current_solution)
        neighbour_objective = objective(neighbour_solution)

        if neighbour_objective < current_best_objective:
            current_solution = neighbour_solution
            current_best_objective = neighbour_objective

            if neighbour_objective < best_objective:
                best_solution = neighbour_solution
                best_objective = neighbour_objective
        else:
            delta = neighbour_objective - current_best_objective
            t = temperature(epoch)
            p_accept = np.exp(-delta / t)
            if np.random.rand() < p_accept:
                current_solution = neighbour_solution

        objective_list.append(current_best_objective)

    return best_objective, best_solution, objective_list


In [127]:
import numpy as np
import matplotlib.pyplot as plt

# Load the distance matrix from file
distances = np.load('distances.npy')

# Define the objective function

# Run simulated annealing and get the objective values
objective, solution, objective_list = run_simulated_annealing(
    initial_solution,
    objective,
    sample_neighbour,
    n_epochs=20,
    temperature=compute_temperature,
)

# Create a line plot of the objective values
plt.plot(objective_list)
plt.xlabel('Iteration')
plt.ylabel('Objective Value')
plt.title('Simulated Annealing')
plt.show()

NameError: name 'objective_function' is not defined

In [30]:
import collections

def run_simulated_annealing(
    initial_solution,
    objective,
    sample,
    n_epochs,
    temperature,
):
    """Run simulated annealing

    Parameters
    ----------
    initial_solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the initial solution.
    objective : callable
        Objective function of the following signature:
        (solution: ndarray of shape (n_cities,)) -> float.
    sample : callable
        A function to sample a neighbouring solution.
        This should have the following signature:
        (solution: ndarray of shape (n_cities,))
        -> ndarray of shape (n_cities,).
    n_epochs : int
        Number of epochs
    temperature : callable
        A function to compute the temperature.
        This should have the following signature:
        (epoch: int) -> float.

    Returns
    -------
    objective : float
        The objective value of the best solution found.
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the best solution found.
    objective_list : list of float
        The objective values of the iterates
    """
    best_solution = initial_solution.copy()  # Store the best solution on this variable.
    best_objective = objective(initial_solution)  # Store the obj. value of `best_solution` on this.
    objective_list = [best_objective]  # List to store the objective values of the iterate.

    for epoch in range(n_epochs):
        current_solution = sample(best_solution)
        current_objective = objective(current_solution)
        temperature_val = temperature(epoch)
        delta = current_objective - best_objective

        if delta < 0:
            best_solution = current_solution.copy()
            best_objective = current_objective
        elif np.exp(-delta / temperature_val) > np.random.rand():
            best_solution = current_solution.copy()

        objective_list.append(best_objective)

    return SolverResult(best_objective, best_solution, objective_list)


SolverResult = collections.namedtuple(
    "SolverResult", "objective solution objective_list"
)

In [ ]:


def main():
    """Run the main routine of this script"""
    distance_matrix_file_path = "distances.npy"

    with open(distance_matrix_file_path, "rb") as f:
        distances = np.load(f)

    # Run the greedy heuristic and obtain a solution.
    initial_solution = run_greedy_heuristic(distances)

    # Test the output.
    shape = (len(distances),)

    np.testing.assert_equal(type(initial_solution), np.ndarray)
    np.testing.assert_equal(initial_solution.shape, shape)

    # Test output of `sample_two_opt` as well.

    sampled_solution = sample_two_opt(initial_solution)

    np.testing.assert_equal(type(sampled_solution), np.ndarray)
    np.testing.assert_equal(sampled_solution.shape, shape)

    # Run simulated annealing and plot the result.
    n_epochs = 5000
    temperature = lambda epoch: 100 / np.log(epoch + 2)
    objective = lambda solution: compute_total_distance(solution, distances)

    objective_list = []
    for i in range(20):
        result = run_simulated_annealing(
            initial_solution,
            objective,
            sample_two_opt,
            n_epochs,
            temperature,
        )
        objective_list.append(result.objective)

    # Plot the objective values of the iterates.
    fig, ax = plt.subplots()
    ax.plot(object)


In [32]:

# Load the distance matrix from the file
distances = np.load("distances.npy")


# Define the objective function for TSP
def tsp_objective(solution):
    return sum([distances[solution[i], solution[i+1]] for i in range(len(solution)-1)]) + distances[solution[-1], solution[0]]


# Define the sample function to generate neighbouring solutions
def tsp_sample(solution):
    # Swap two cities randomly
    idx1, idx2 = np.random.choice(len(solution), 2, replace=False)
    new_solution = solution.copy()
    new_solution[idx1], new_solution[idx2] = new_solution[idx2], new_solution[idx1]
    return new_solution


# Define the temperature function
def tsp_temperature(epoch):
    return 1 / np.log(epoch + 2)


# Set the number of epochs and the initial solution
n_epochs = 10000
initial_solution = np.arange(len(distances))


# Run simulated annealing 20 times and store the objective values of the iterates
objective_lists = []
for i in range(20):
    result = run_simulated_annealing(
        initial_solution,
        tsp_objective,
        tsp_sample,
        n_epochs,
        tsp_temperature,
    )
    objective_lists.append(result.objective_list)


# Plot the objective values of the iterates
fig, ax = plt.subplots(figsize=(8, 6))
for i, objective_list in enumerate(objective_lists):
    ax.plot(objective_list)


AttributeError: module 'matplotlib' has no attribute 'subplots'