In [1]:
import os

#import matplotlib.pyplot as plt

import numpy as np

Exercise 1 

In [2]:

def compute_total_cost(solution, distances):
    """Compute the total cost of a given solution

    Examples
    --------
    >>> solution = np.array([0, 1, 2, 3, 4, 5])
    >>> distances = np.array([
    ...    [0, 5, 3, 4, 2, 3],
    ...    [5, 0, 2, 8, 3, 9],
    ...    [3, 2, 0, 2, 5, 8],
    ...    [4, 8, 2, 0, 6, 9],
    ...    [2, 3, 5, 6, 0, 1],
    ...    [3, 9, 8, 9, 1, 0],
    ... ], dtype=float)
    >>> compute_total_cost(solution, distances)
    19.0

    Parameters
    ----------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the solution whose length is to be computed.
    distances : ndarray
        2D array of shape (n_cities, n_cities) with `float` dtype
        representing the distance matrix.

    Returns
    -------
    length : float
    """
    # Question 1
    n_cities = solution.shape[0]
    cost = 0.0
    for i in range(n_cities):
        j = (i + 1) % n_cities
        cost += distances[solution[i], solution[j]]
    return cost

In [3]:
#test
solution = np.array([0, 1, 2, 3, 4, 5])
distances = np.array([[0, 5, 3, 4, 2, 3],
                      [5, 0, 2, 8, 3, 9],
                      [3, 2, 0, 2, 5, 8],
                      [4, 8, 2, 0, 6, 9],
                      [2, 3, 5, 6, 0, 1],
                      [3, 9, 8, 9, 1, 0],
                      ], dtype=float)
compute_total_cost(solution, distances)

19.0

Exercise 2

In [1]:

def run_greedy_heuristic(distances):
    """Run a greedy heuristic for TSP

    This runs a greedy heuristic for TSP and return a feasible solution.
    This starts at city 0 and creates a soltuion by finding the shortest
    cities greedily.

    Examples
    --------
    >>> distances = np.array([
    ...    [0, 5, 3, 4, 2, 3],
    ...    [5, 0, 2, 8, 3, 9],
    ...    [3, 2, 0, 2, 5, 8],
    ...    [4, 8, 2, 0, 6, 9],
    ...    [2, 3, 5, 6, 0, 1],
    ...    [3, 9, 8, 9, 1, 0],
    ... ], dtype=float)
    >>> run_greedy_heuristic(distances)
    array([0, 4, 5, 2, 1, 3])
    >>> compute_total_cost(run_greedy_heuristic(distances), distances)
    25.0

    Parameters
    ----------
    distances : ndarray
        2D array of shape (n_cities, n_cities) with `float` dtype
        representing the distance matrix.

    Returns
    -------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the solution obtained by the greedy heuristic.
    """

    c = 0
    x = c.sort()

In [ ]:
    
distances = np.array([
    [0, 5, 3, 4, 2, 3],
    [5, 0, 2, 8, 3, 9],
    [3, 2, 0, 2, 5, 8],
    [4, 8, 2, 0, 6, 9],
    [2, 3, 5, 6, 0, 1],
    [3, 9, 8, 9, 1, 0],], dtype=float)

    run_greedy_heuristic(distances)
    array([0, 4, 5, 2, 1, 3])
    compute_total_cost(run_greedy_heuristic(distances), distances)
    #25.0

Exercise 3

In [21]:
import random


def sample_two_opt(solution):
    """Return a neighbour of a given solution based on two-opt

    This returns a neighbouring solution.

    Examples
    --------
    >>> solution = np.array([0, 1, 2, 3])
    >>> sample_two_opt(solution)  # doctest: +SKIP
    array([0, 2, 1, 3])

    Parameters
    ----------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the current solution.

    Returns
    -------
    new_solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the sampled solution.
    """
    n_cities = len(solution)
    i, j = sorted(random.sample(range(n_cities), 2))
    new_solution = np.concatenate((solution[:i], solution[i:j+1][::-1], solution[j+1:]))
    return new_solution

solution = np.array([0, 1, 2, 3])


print(sample_two_opt(solution))

[0 1 3 2]


In [ ]:
import random


def sample_two_opt(solution):
    """Return a neighbour of a given solution based on two-opt

    This returns a neighbouring solution.

    Examples
    --------
    >>> solution = np.array([0, 1, 2, 3])
    >>> sample_two_opt(solution)  # doctest: +SKIP
    array([0, 2, 1, 3])

    Parameters
    ----------
    solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the current solution.

    Returns
    -------
    new_solution : ndarray
        1D array of shape (n_cities,) with `int` dtype representing
        the sampled solution.
    """
    n_cities = len(solution)
    i, j = sorted(random.sample(range(n_cities), 2))
    new_solution = np.concatenate((solution[:i], solution[i:j+1][::-1], solution[j+1:]))
    return new_solution

solution = np.array([0, 1, 2, 3])


print(sample_two_opt(solution))

In [ ]:
def two_opt(solution, dist_matrix):
    n_cities = len(solution)
    improve = True
    best_distance = np.inf

    while improve:
        improve = False
        for i in range(1, n_cities - 1):
            for j in range(i + 1, n_cities):
                if j - i == 1:
                    continue  # Ignore adjacent edges
                new_solution = solution.copy()
                new_solution[i:j] = solution[j - 1:i - 1:-1]  # Reverse subsequence
                new_distance = calculate_distance(new_solution, dist_matrix)
                if new_distance < best_distance:
                    solution = new_solution
                    best_distance = new_distance
                    improve = True
        if improve:
            print(f"Improved distance: {best_distance:.2f}")
    return solution, best_distance